import { Fade, TextField } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import { Camera, GitHub, Info } from "react-feather";

const Home: NextPage = () => {
  const [animation, setAnimation] = useState<boolean>(true);
  const animationTime: number = 300;
  // const step1 = () => {
  //   return (
  //     <>
  //       <div className="d-flex flex-column mt-5">
  //         <span className="card__title">شماره تلفن همراه خود را وارد کنید</span>
  //         <div className="mt-2 card-input">
  //           <FormControl
  //             className=" py-3 px-2 "
  //             id="step1"
  //             autoFocus={true}
  //             value={mobile}
  //             onChange={(e) => setMobile(e.target.value)}
  //           />
  //         </div>
  //         <div className="card__info mt-2 mb-4">
  //           <InfoOutlined />
  //           <span className="mx-1 ">
  //             پیامک کد فعالسازی به این شماره تلفن همراه ارسال می شود
  //           </span>
  //         </div>
  //       </div>

  //       <div className="card-btn">
  //         <Button
  //           type="button "
  //           className="w-100 py-3"
  //           size="lg"
  //           onClick={() => {
  //             if (mobile.length > 9 && mobile.length < 12 && mobile !== "") {
  //               login();
  //             }
  //           }}
  //         >
  //           دریافت کد فعالسازی
  //         </Button>
  //       </div>
  //     </>
  //   );
  // };

  const myloader = ({ src }: { src: string }): string => {
    return src;
  };
  return (
    <div className="bg-hrm-bg min-h-screen p-10 h-full w-full bg-no-repeat object-contain bg-cover bg-right-bottom">
      <Head>
        <title>HRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="">
        <Image
          src={"/login/kashanplus-logo.svg"}
          alt="kashanplus-logo"
          layout="intrinsic"
          width={300}
          height={50}
          loader={myloader}
          unoptimized
        />
      </div>

      <div className="flex justify-center items-center w-100">
        <div className="bg-white shadow-normal w-1/3 rounded-lg p-4 mx-2 d-flex flex-column justify-content-around ">
          <div className="">
            <Image
              src="/logo.svg"
              alt=""
              layout="responsive"
              width={30}
              height={10}
              loader={myloader}
              unoptimized
            />
          </div>
          <Fade in={animation} timeout={animationTime}>
            {/* <div className="">{renderStep()}</div> */}
            <div className="dir-rtl">
              <div className="text-2xl mt-5 ">
                شماره تلفن همراه خود را وارد کنید
              </div>
              <div className="dir-rtl mt-1">
                <TextField
                  className="w-full hide-arrow mt-2 "
                  error={true}
                  type="number"
                />
              </div>
              <div className="flex mt-2 mb-5">
                <Camera color="red" size={48} />
                <Info color="red" size={48} />
                <GitHub color="red" size={48} />
                {/* <FontAwesomeIcon icon={faInfoCircle} style={{ fontSize: 20 }} /> */}
                <span className="mr-1 text-sm ">
                  پیامک کد فعالسازی به این شماره تلفن همراه ارسال می شود
                </span>
              </div>

              <div className="">
                <button className=" bg-primary w-full text-2xl  hover:bg-blue-600 text-white font-bold py-3 px-4 rounded">
                  دریافت کد فعالسازی
                </button>
              </div>
            </div>
          </Fade>
        </div>
      </div>
    </div>
  );
};

export default Home;
